# Generated by Django 3.2.1 on 2021-09-20 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('model', models.CharField(max_length=25)),
                ('manufacturing_date', models.DateField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='car.brand')),
            ],
            options={
                'ordering': ['updated'],
            },
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['brand'], name='car_car_brand_i_5ad160_idx'),
        ),
    ]
